@startuml
actor "Comprador" as actorComprador
boundary "<<Pantalla>>\nDatosDelVuelo" as boundryPantallaDatosDelVuelo

actorComprador -> boundryPantallaMetodoPago
activate boundryPantallaMetodoPago
   boundryPantallaMetodoPago -> boundryPantallaMetodoPago: getSucursales()
    activate boundryPantallaMetodoPago
        control "SucursalesController" as sucursalesController
            control "SucursalesModel" as sucursalesModel
           boundryPantallaMetodoPago -> sucursalesController: GET api/v1/sucursales: Sucursales[]
            activate sucursalesController
                sucursalesController -> sucursalesModel: getAllSucursales()
                activate sucursalesController
                    database "bd_comprodigios" as dbComprodigios
                    entity sucursales
                    activate sucursalesModel
                        activate sucursalesModel
                            sucursalesModel -> dbComprodigios: SQL query
                            dbComprodigios -> sucursales
                            dbComprodigios -> sucursalesModel: {id, nombreCompleto, iataCode}
                        deactivate

                    deactivate
                deactivate
        deactivate
    deactivate
deactivate
@enduml